import { test, expect, type Page, type Locator } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner } from './helpers/ui';
import { apiLogin, deleteScenarioById, archiveScenario, type ApiSession } from './helpers/scenarioApi';

/**
 * Archiving from the generic admin list (Entity.vue on an archivable store).
 *
 * The admin scenarios page is the first consumer of the framework-level
 * archive support: the "show archived" toggle in the toolbar, the archive /
 * restore row action and the archived badge all come from Entity.vue, not
 * from the page. What is pinned here is what the administrator sees.
 */

const ADMIN_EMAIL = process.env.E2E_ADMIN_EMAIL || '1.supervisor@test.com';
const ADMIN_PASSWORD = process.env.E2E_ADMIN_PASSWORD || 'test';
const API_BASE = process.env.OCF_API_URL || 'http://localhost:8080/api/v1';

const RUN_STAMP = Date.now().toString(36);
const HIDDEN_TITLE = `E2E admin archive hidden ${RUN_STAMP}`;
const TOGGLED_TITLE = `E2E admin archive toggled ${RUN_STAMP}`;

let admin: ApiSession;
let hiddenScenarioId: string | null = null;
let toggledScenarioId: string | null = null;
/** True once ocf-core hides archived rows by default (ocf-core#489). */
let backendHidesArchived = false;

async function createScenario(session: ApiSession, title: string): Promise<string> {
  const res = await session.api.post(`${API_BASE}/scenarios`, {
    headers: { Authorization: `Bearer ${session.token}` },
    data: {
      name: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      title,
      description: 'Auto-generated by admin-scenarios-archive.spec.ts — safe to delete.',
      os_type: 'deb',
      instance_type: 'xs',
      difficulty: 'beginner',
      source_type: 'builtin',
    },
  });
  if (!res.ok()) throw new Error(`create scenario failed: ${res.status()} ${await res.text()}`);
  return (await res.json()).id;
}

/**
 * Before ocf-core#489 the generic list neither hides archived rows nor knows
 * the include_archived parameter (an unknown parameter is a 404 there). The
 * spec probes once so the toggle scenario is skipped, not falsely failed, on
 * such a backend.
 */
async function probeIncludeArchived(session: ApiSession): Promise<boolean> {
  const res = await session.api.get(`${API_BASE}/scenarios?cursor=&limit=1&include_archived=true`, {
    headers: { Authorization: `Bearer ${session.token}` },
  });
  return res.ok();
}

/** The admin list row for a scenario title. */
function scenarioRow(page: Page, title: string): Locator {
  return page.locator('li.entity-item').filter({ hasText: title });
}

/**
 * Geometry inside a row once nothing transient acts on it: the row scales up
 * and its card lifts under the mouse, both with a transition, which would
 * read as a layout shift right after a click. The pointer is parked and both
 * transforms left to settle before measuring.
 */
async function settledBox(page: Page, row: Locator, target: Locator) {
  await page.mouse.move(0, 0);
  for (const animated of [row, row.locator('.entity-card').first()]) {
    await expect
      .poll(() => animated.evaluate((el) => getComputedStyle(el).transform))
      .toBe('none');
  }
  return target.boundingBox();
}

/**
 * Administration → Scenarios → Scenarios, through the sidebar like an
 * administrator does. Specs never page.goto() inside the product.
 */
async function openAdminScenarios(page: Page): Promise<void> {
  // The administration link lives in the sidebar's collapsed "More" section.
  const adminLink = page.locator('.admin-link');
  if (!(await adminLink.isVisible().catch(() => false))) {
    await page.locator('.menu-bottom-toggle').click();
  }
  await adminLink.click();
  const category = page.locator('.nav-menu-shell [data-category="scenarios"]');
  await expect(category).toBeVisible();
  const itemList = category.locator('.category-items');
  if (!(await itemList.evaluate((el) => el.classList.contains('expanded')))) {
    await category.locator('.category-header').click();
    await expect(itemList).toHaveClass(/expanded/);
  }
  await category.locator('a[href="/admin/scenarios"]').click();
  await expect(page.locator('.toolbar h2')).toBeVisible();
}

test.beforeAll(async () => {
  admin = await apiLogin(ADMIN_EMAIL, ADMIN_PASSWORD);
  backendHidesArchived = await probeIncludeArchived(admin);
  hiddenScenarioId = await createScenario(admin, HIDDEN_TITLE);
  toggledScenarioId = await createScenario(admin, TOGGLED_TITLE);
  await archiveScenario(admin, hiddenScenarioId);
});

test.afterAll(async () => {
  if (hiddenScenarioId) await deleteScenarioById(admin, hiddenScenarioId);
  if (toggledScenarioId) await deleteScenarioById(admin, toggledScenarioId);
  await admin?.api.dispose();
});

test('archived scenario disappears from the admin list by default and reappears with the toggle', async ({
  page,
}) => {
  test.skip(
    !backendHidesArchived,
    'the running ocf-core does not hide archived rows nor accept include_archived yet (ocf-core#489)'
  );
  test.setTimeout(120_000);

  await login(page, ADMIN_EMAIL, ADMIN_PASSWORD);
  await dismissVerificationBanner(page);
  await openAdminScenarios(page);

  await expect(scenarioRow(page, TOGGLED_TITLE), 'a scenario in service is listed').toBeVisible({
    timeout: 15_000,
  });
  await expect(scenarioRow(page, HIDDEN_TITLE), 'an archived one is not, by default').toHaveCount(0);

  await page.locator('[data-test="entity-show-archived"]').check();

  const archived = scenarioRow(page, HIDDEN_TITLE);
  await expect(archived, 'the toggle brings it back').toBeVisible({ timeout: 15_000 });
  await expect(archived.locator('[data-test="entity-archived-badge"]'), 'badged as archived').toBeVisible();
  await expect(archived.locator('[data-test="entity-archive-toggle"]'), 'and offering Restore').toHaveText(/restore|restaurer/i);
});

test('archive then restore from the row action updates the badge without a layout shift', async ({
  page,
}) => {
  test.setTimeout(120_000);

  await login(page, ADMIN_EMAIL, ADMIN_PASSWORD);
  await dismissVerificationBanner(page);
  await openAdminScenarios(page);

  const row = scenarioRow(page, TOGGLED_TITLE);
  await expect(row).toBeVisible({ timeout: 15_000 });
  await row.scrollIntoViewIfNeeded();

  const badge = row.locator('[data-test="entity-archived-badge"]');
  const action = row.locator('[data-test="entity-archive-toggle"]');
  await expect(badge, 'a scenario in service carries no visible badge').toBeHidden();
  await expect(action).toHaveText(/archive|archiver/i);

  // The badge lives in the card header; the row action in the actions column.
  // The column's y is left out on purpose: it is centred on the card body,
  // whose height follows the DTO the backend answers with — the pre-#489
  // scenario handler answers a hand-built DTO that differs from the list's.
  const header = row.locator('.entity-card-header');
  const actions = row.locator('.actions');
  const sizeAndX = (box: { x: number; width: number; height: number } | null) =>
    box && { x: box.x, width: box.width, height: box.height };
  const headerBefore = await settledBox(page, row, header);
  const actionsBefore = sizeAndX(await settledBox(page, row, actions));
  expect(headerBefore).not.toBeNull();
  expect(actionsBefore).not.toBeNull();

  await action.click();

  await expect(badge, 'archiving shows the badge in place').toBeVisible({ timeout: 15_000 });
  await expect(action, 'and the same button now offers Restore').toHaveText(/restore|restaurer/i);
  expect(await settledBox(page, row, header), 'the header did not move or grow').toEqual(headerBefore);
  expect(sizeAndX(await settledBox(page, row, actions)), 'nor did the actions column').toEqual(actionsBefore);

  await action.click();

  await expect(badge, 'restoring clears the badge').toBeHidden({ timeout: 15_000 });
  await expect(action).toHaveText(/archive|archiver/i);
  expect(await settledBox(page, row, header), 'still no shift after restore').toEqual(headerBefore);
  expect(sizeAndX(await settledBox(page, row, actions))).toEqual(actionsBefore);
});
