import { test, expect } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importPlatformScenario,
  deleteScenarioById,
  getAvailableScenario,
  getMyScenarioSessions,
  getTerminalSession,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { readFlagFileFromTerminal, waitForLiveTerminal } from './helpers/xterm';
import { adminSession } from './helpers/freshUsers';

// ---------------------------------------------------------------------------
// Tier B — pause a scenario run and resume it at the same step.
//
// karim launches a 3-step fixture, passes step 1, reads the flag of step 2 in
// the real xterm, then pauses the run with Stop. The run must stay open: the
// launcher card shows it paused, Resume leads back to the session view, whose
// paused banner starts the terminal again — and the panel is still on step 2,
// with the container still holding the SAME flag (disk preserved, same run).
// Submitting that flag moves on to step 3.
//
// The fixture goes into the PLATFORM catalogue through an admin: public is a
// platform notion, so an org import would be invisible to the learner.
//
// Requirements (local only): ocf-core on :8080, vite, tt-backend with a live
// Incus behind it, an 'apk'-compatible distribution, a platform admin
// (E2E_ADMIN_EMAIL), and a learner plan with data persistence (Stop only
// exists on persistent terminals). The spec SELF-SKIPS when any of that is
// missing. Structure copied from scenario-run.spec.ts.
// ---------------------------------------------------------------------------

const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E pause resume ${RUN_STAMP}`;
const FLAG_PATH = '/tmp/e2e-pause-flag';

let admin: ApiSession | null = null;
let learner: ApiSession;
let scenarioId: string | null = null;
let launchable = false;

test.beforeAll(async () => {
  admin = await adminSession();
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  if (!admin) return;

  const scenario = await importPlatformScenario(admin, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-pause-resume.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    intro_text: 'Welcome to the pause/resume fixture.',
    finish_text: 'Fixture complete.',
    steps: [
      { title: 'Read the briefing', step_type: 'info', text_content: 'Just read and continue.' },
      {
        title: 'Capture the flag',
        step_type: 'flag',
        has_flag: true,
        flag_path: FLAG_PATH,
        text_content: 'The flag hides in /tmp — cat it and submit.',
      },
      { title: 'All done', step_type: 'info', text_content: 'You made it through a pause.' },
    ],
  });
  scenarioId = scenario.id;

  const card = await getAvailableScenario(learner, FIXTURE_TITLE);
  launchable = !!card?.launchable;
});

test.afterAll(async () => {
  if (scenarioId) {
    await cleanupScenarioSession(learner, scenarioId).catch(() => {});
    if (admin) await deleteScenarioById(admin, scenarioId);
  }
  await admin?.api.dispose();
  await learner?.api.dispose();
});

test('learner pauses a scenario run and resumes it at the same step', async ({ page }) => {
  test.skip(!admin, 'no platform admin to import the fixture — set E2E_ADMIN_EMAIL / E2E_ADMIN_PASSWORD');
  test.skip(
    !launchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  // Two terminal starts (launch + resume) plus step transitions.
  test.setTimeout(480_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    const toastText = (await errorToast.innerText().catch(() => '')) || 'launch refused';
    test.skip(true, `launch refused by the backend (likely host capacity): ${toastText.slice(0, 120)}`);
  }
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the briefing', {
    timeout: 60_000,
  });

  // Step 1 — pass it.
  await page.getByTestId('scenario-info-ack').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', {
    timeout: 30_000,
  });

  // Step 2 — read the flag, but do not submit it yet.
  await waitForLiveTerminal(page);
  const flagBefore = await readFlagFileFromTerminal(page, FLAG_PATH);

  // Pause. Stop only exists on a persistent terminal: without data
  // persistence on the learner's plan there is nothing to pause. Decided from
  // the terminal record, not from the button being absent — a missing Stop on
  // a persistent run is exactly the kind of regression this spec must catch.
  const terminalId = page.url().split('/terminal-session/')[1]?.split(/[?#]/)[0];
  const terminal = await getTerminalSession(learner, terminalId);
  test.skip(
    terminal?.persistence_mode !== 'persistent',
    'terminal is not persistent — the learner plan has no data persistence, so runs cannot pause'
  );
  // The accessible name carries the icon glyph before the label, so anchor
  // on the end only.
  const stopButton = page.getByRole('button', { name: /(Stop|Arrêter)$/ });
  await expect(stopButton).toBeEnabled({ timeout: 15_000 });
  await stopButton.click();
  await expect(page.getByTestId('resume-session-cta')).toBeVisible({ timeout: 60_000 });

  // The run is still open, and says so: paused, from the launcher.
  await expect
    .poll(
      async () => {
        const sessions = await getMyScenarioSessions(learner);
        const s = sessions.find((x) => x.scenario_id === scenarioId);
        return s && { status: s.status, resume_mode: s.resume_mode };
      },
      { timeout: 30_000 }
    )
    .toEqual({ status: 'active', resume_mode: 'paused' });

  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
  const pausedCard = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(pausedCard.getByTestId('scenario-paused-badge')).toBeVisible({ timeout: 15_000 });

  // Resume from the card, then restart the terminal from the paused banner.
  await pausedCard.getByTestId('scenario-resume-btn').click();
  await page.waitForURL(/\/terminal-session\//, { timeout: 30_000 });
  await page.getByTestId('resume-session-cta').click();

  // Same step, same container, same flag.
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', {
    timeout: 120_000,
  });
  await waitForLiveTerminal(page, 120_000);
  const flagAfter = await readFlagFileFromTerminal(page, FLAG_PATH);
  expect(flagAfter).toBe(flagBefore);

  await page.getByTestId('scenario-flag-input').fill(flagAfter);
  await page.getByTestId('scenario-flag-submit').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('All done', {
    timeout: 30_000,
  });
});
