import { test, expect, type Page } from '@playwright/test';
import { login, loginFresh } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenario,
  getAvailableScenario,
  createGroupAssignment,
  updateAssignment,
  deleteAssignment,
  findTeacherGroup,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';

// ---------------------------------------------------------------------------
// Tier B — who may see a scenario, and what the launcher offers once a run
// has started. Two independent guarantees, one file:
//
//  1. The assignment window IS the visibility rule for a non-public scenario:
//     invisible unassigned, visible assigned, invisible again once the deadline
//     has passed. All three states are read off the real launcher page.
//  2. A learner with a live session is offered Resume, never a second Launch —
//     a terminal carries one scenario for its whole life, so a duplicate launch
//     would strand the first run.
//
// Only the second test provisions a container, so the assignment gating still
// runs on a host too busy to start one.
//
// Class choice — deliberate, and NOT marc's class: the launcher scopes group
// assignments to the CURRENT ORG CONTEXT (see GetAvailableScenarios), and
// karim is a member of marc's class without being a member of marc-corp
// itself. He therefore cannot select that org and cannot reach the assignment
// through the UI at all. This spec uses the class whose org karim actually
// belongs to; the marc-corp case is reported separately as a product defect.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_ORG_MANAGER_EMAIL || 'nadia@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const GATED_TITLE = `E2E gated ${RUN_STAMP}`;
const RESUMABLE_TITLE = `E2E resumable ${RUN_STAMP}`;

let trainer: ApiSession;
let learner: ApiSession;
let orgId: string | null = null;
let groupId: string | null = null;
let gatedScenarioId: string | null = null;
let resumableScenarioId: string | null = null;
let assignmentId: string | null = null;
let resumableLaunchable = false;

/** The learner's launcher card for a title, however many other cards are up. */
function scenarioCard(page: Page, title: string) {
  return page.getByTestId('scenario-card').filter({ hasText: title });
}

/**
 * Re-enter the launcher the way a learner would after doing something else,
 * so the page refetches its scenario list. Specs never page.goto() inside the
 * product, and a reload would not show WHERE the user went.
 */
async function revisitLauncher(page: Page): Promise<void> {
  await navigateViaMenuCategory(page, 'scenarios', '/my-scenarios');
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
}

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);

  const group = await findTeacherGroup(trainer, /test class/i, 1);
  if (!group) return;
  groupId = group.group_id;
  orgId = group.organization_id;

  const gated = await importScenario(trainer, orgId, {
    title: GATED_TITLE,
    description: 'Auto-generated by scenario-assignment.spec.ts — safe to delete.',
    is_public: false,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  gatedScenarioId = gated.id;

  const resumable = await importScenario(trainer, orgId, {
    title: RESUMABLE_TITLE,
    description: 'Auto-generated by scenario-assignment.spec.ts — safe to delete.',
    is_public: true,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  resumableScenarioId = resumable.id;

  const card = await getAvailableScenario(learner, RESUMABLE_TITLE);
  resumableLaunchable = !!card?.launchable;
});

test.afterAll(async () => {
  if (assignmentId) await deleteAssignment(trainer, assignmentId);
  if (resumableScenarioId) {
    await cleanupScenarioSession(learner, resumableScenarioId).catch(() => {});
  }
  if (orgId) {
    if (gatedScenarioId) await deleteScenario(trainer, orgId, gatedScenarioId);
    if (resumableScenarioId) await deleteScenario(trainer, orgId, resumableScenarioId);
  }
  await trainer?.api.dispose();
  await learner?.api.dispose();
});

test('the assignment window decides whether a non-public scenario reaches the learner', async ({
  page,
}) => {
  test.skip(!groupId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.setTimeout(120_000);

  await loginFresh(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  await expect(
    scenarioCard(page, GATED_TITLE),
    'an unassigned non-public scenario must not be offered'
  ).toHaveCount(0);

  const assignment = await createGroupAssignment(trainer, gatedScenarioId!, groupId!);
  assignmentId = assignment.id;

  await revisitLauncher(page);
  const assigned = scenarioCard(page, GATED_TITLE);
  await expect(assigned, 'an assigned scenario must be offered').toBeVisible({ timeout: 15_000 });
  await expect(assigned.getByTestId('scenario-launch-btn')).toBeVisible();

  await updateAssignment(trainer, assignmentId!, {
    deadline: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  });

  await revisitLauncher(page);
  await expect(
    scenarioCard(page, GATED_TITLE),
    'a past deadline must close the scenario again'
  ).toHaveCount(0);
});

test('a learner with a live session is offered Resume instead of a second Launch', async ({
  page,
}) => {
  test.skip(!groupId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.skip(
    !resumableLaunchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = scenarioCard(page, RESUMABLE_TITLE);
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  // A busy host refuses the launch with an error toast instead of navigating —
  // an environment condition, not a product defect.
  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    const toastText = (await errorToast.innerText().catch(() => '')) || 'launch refused';
    test.skip(true, `launch refused by the backend (likely host capacity): ${toastText.slice(0, 120)}`);
  }
  await expect(page.getByTestId('scenario-step-title')).toBeVisible({ timeout: 60_000 });

  await revisitLauncher(page);
  const started = scenarioCard(page, RESUMABLE_TITLE);
  await expect(started.getByTestId('scenario-resume-btn')).toBeVisible({ timeout: 15_000 });
  await expect(started.getByTestId('scenario-launch-btn')).toHaveCount(0);
});
