import { test, expect, type Page } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenarioById,
  getAvailableScenario,
  getMyScenarioSessions,
  getTerminalSession,
  getScenarioSessionByTerminal,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { readFlagFileFromTerminal, waitForLiveTerminal } from './helpers/xterm';
import { adminSession } from './helpers/freshUsers';

// ---------------------------------------------------------------------------
// Tier B — pause a scenario run and resume it at the same step.
//
// karim launches a 3-step fixture, passes step 1, reads the flag of step 2 in
// the real xterm, then pauses the run with Stop. The run must stay open: the
// launcher card shows it paused, Resume leads back to the session view, whose
// paused banner starts the terminal again — and the panel is still on step 2,
// with the container still holding the SAME flag (disk preserved, same run).
// Submitting that flag moves on to step 3.
//
// The fixture goes into the PLATFORM catalogue through an admin: public is a
// platform notion, so an org import would be invisible to the learner.
//
// Requirements (local only): ocf-core on :8080, vite, tt-backend with a live
// Incus behind it, an 'apk'-compatible distribution, a platform admin
// (E2E_ADMIN_EMAIL). The spec SELF-SKIPS when that infrastructure is
// missing. The learner's plan is part of the fixture and must have a CPU/RAM
// budget and data persistence (Stop only exists on persistent terminals): the
// spec FAILS, loudly, when it does not. Structure copied from scenario-run.spec.ts.
// ---------------------------------------------------------------------------

const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E pause resume ${RUN_STAMP}`;
const FLAG_PATH = '/tmp/e2e-pause-flag';

let admin: ApiSession | null = null;
let learner: ApiSession;
let scenarioId: string | null = null;
let launchable = false;
let blockReason = '';

test.beforeAll(async () => {
  admin = await adminSession();
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  if (!admin) return;

  const scenario = await importScenario(admin, null, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-pause-resume.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    intro_text: 'Welcome to the pause/resume fixture.',
    finish_text: 'Fixture complete.',
    steps: [
      { title: 'Read the briefing', step_type: 'info', text_content: 'Just read and continue.' },
      {
        title: 'Capture the flag',
        step_type: 'flag',
        has_flag: true,
        flag_path: FLAG_PATH,
        text_content: 'The flag hides in /tmp — cat it and submit.',
      },
      { title: 'All done', step_type: 'info', text_content: 'You made it through a pause.' },
    ],
  });
  scenarioId = scenario.id;

  const card = await getAvailableScenario(learner, FIXTURE_TITLE);
  launchable = !!card?.launchable;
  blockReason = card?.block_reason || '';
});

test.afterAll(async () => {
  if (scenarioId) {
    await cleanupScenarioSession(learner, scenarioId).catch(() => {});
    if (admin) await deleteScenarioById(admin, scenarioId);
  }
  await admin?.api.dispose();
  await learner?.api.dispose();
});

// Preconditions of both tests: the fixture was imported, and the learner's
// plan can launch it.
function requireLaunchableFixture() {
  test.skip(!admin, 'no platform admin to import the fixture — set E2E_ADMIN_EMAIL / E2E_ADMIN_PASSWORD');
  // A plan that cannot fit the machine is a broken fixture, not missing
  // infrastructure: fail on it. Only a missing image/backend skips.
  expect(
    ['size_over_plan', 'budget_exhausted', 'plan'],
    `${LEARNER_EMAIL}'s plan cannot launch the fixture (${blockReason}) — give it a CPU/RAM budget`
  ).not.toContain(blockReason);
  test.skip(
    !launchable,
    `fixture not launchable (${blockReason}) — Tier B needs a live tt-backend + Incus with an apk distribution`
  );
}

// Launches the fixture from its card, passes step 1, reads the flag of step 2
// in the real xterm, then pauses the run with Stop. Returns the flag and the
// paused terminal.
async function launchAndPauseAtFlagStep(page: Page): Promise<{ flagBefore: string; terminalId: string }> {
  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toBeVisible({ timeout: 15_000 });
  // A card whose previous run was abandoned offers Relaunch instead of Launch.
  await card.getByTestId('scenario-launch-btn').or(card.getByTestId('scenario-relaunch-btn')).click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    const toastText = (await errorToast.innerText().catch(() => '')) || 'launch refused';
    test.skip(true, `launch refused by the backend (likely host capacity): ${toastText.slice(0, 120)}`);
  }
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the briefing', {
    timeout: 60_000,
  });

  // Step 1 — pass it.
  await page.getByTestId('scenario-info-ack').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', {
    timeout: 30_000,
  });

  // Step 2 — read the flag, but do not submit it yet.
  await waitForLiveTerminal(page);
  const flagBefore = await readFlagFileFromTerminal(page, FLAG_PATH);

  // Pause. Only a persistent terminal can pause, and the learner's plan is part
  // of the fixture: a plan without data persistence is a broken fixture, so it
  // fails here rather than skipping — and a persistent run without a Stop
  // button fails just below. Read from the terminal record, which carries the
  // persistence ocf-core actually resolved for this launch (org plan included).
  const terminalId = page.url().split('/terminal-session/')[1]?.split(/[?#]/)[0];
  const terminal = await getTerminalSession(learner, terminalId);
  expect(
    terminal?.persistence_mode,
    `${LEARNER_EMAIL}'s effective plan has no data persistence — enable it on the local plan, runs cannot pause without it`
  ).toBe('persistent');
  // The accessible name carries the icon glyph before the label, so anchor
  // on the end only.
  const stopButton = page.getByRole('button', { name: /(Stop|Arrêter)$/ });
  await expect(stopButton).toBeEnabled({ timeout: 15_000 });
  await stopButton.click();
  await expect(page.getByTestId('resume-session-cta')).toBeVisible({ timeout: 60_000 });

  return { flagBefore, terminalId };
}

// Waits until ocf-core reports the learner's run of the fixture as open, and
// resumable the given way.
async function expectRunResumeMode(resumeMode: 'paused' | 'rebuild') {
  await expect
    .poll(
      async () => {
        const sessions = await getMyScenarioSessions(learner);
        const s = sessions.find((x) => x.scenario_id === scenarioId && x.status === 'active');
        return s && { status: s.status, resume_mode: s.resume_mode };
      },
      { timeout: 30_000 }
    )
    .toEqual({ status: 'active', resume_mode: resumeMode });
}

// Same step, same flag: submitting what the learner read before moves on.
async function submitFlagAndFinish(page: Page, flagBefore: string) {
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', {
    timeout: 120_000,
  });
  await waitForLiveTerminal(page, 120_000);
  const flagAfter = await readFlagFileFromTerminal(page, FLAG_PATH);
  expect(flagAfter).toBe(flagBefore);

  await page.getByTestId('scenario-flag-input').fill(flagAfter);
  await page.getByTestId('scenario-flag-submit').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('All done', {
    timeout: 30_000,
  });
}

test('learner pauses a scenario run and resumes it at the same step', async ({ page }) => {
  requireLaunchableFixture();
  // Two terminal starts (launch + resume) plus step transitions.
  test.setTimeout(480_000);

  const { flagBefore } = await launchAndPauseAtFlagStep(page);

  // The run is still open, and says so: paused, from the launcher.
  await expectRunResumeMode('paused');

  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
  const pausedCard = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(pausedCard.getByTestId('scenario-paused-badge')).toBeVisible({ timeout: 15_000 });

  // Resume from the card, then restart the terminal from the paused banner.
  await pausedCard.getByTestId('scenario-resume-btn').click();
  await page.waitForURL(/\/terminal-session\//, { timeout: 30_000 });
  await page.getByTestId('resume-session-cta').click();

  // Same container: the disk kept the flag.
  await submitFlagAndFinish(page, flagBefore);
});

// ---------------------------------------------------------------------------
// Rebuild and resume. The learner deletes the paused terminal: the container
// is gone, but the run is not over. The card offers Rebuild & resume, which
// builds a NEW terminal at step 2 — the scenario setup and the background of
// every step up to 2 replayed, the flag re-planted from the stored value — so
// the flag read before the delete is still the one accepted.
// ---------------------------------------------------------------------------
test('learner deletes a paused run\'s terminal, rebuilds it and resumes at the same step', async ({ page }) => {
  requireLaunchableFixture();
  // Launch, rebuild (a new terminal plus the replay) and step transitions.
  test.setTimeout(600_000);
  // The previous test leaves its run open on the last step.
  await cleanupScenarioSession(learner, scenarioId!);

  const { flagBefore, terminalId } = await launchAndPauseAtFlagStep(page);

  // Delete the paused terminal from its banner.
  await page.getByTestId('delete-session-cta').click();
  // Deleting keeps the run: the confirm must not say everything is lost.
  // (The exact copy, both languages, is pinned in the component test.)
  await expect(page.locator('.base-modal-container')).not.toContainText(/permanently lost|perdus définitivement/i);
  await page.getByTestId('confirm-delete-cta').click();
  await page.waitForURL((url) => !url.pathname.includes(terminalId), { timeout: 30_000 });

  // The run is still open: its container is gone, so it is rebuilt.
  await expectRunResumeMode('rebuild');
  // What the session view of the deleted terminal reads to offer the rebuild:
  // the terminal is still listed, as deleted, and its run says how to resume.
  expect((await getTerminalSession(learner, terminalId))?.state).toBe('deleted');
  expect((await getScenarioSessionByTerminal(learner, terminalId))?.resume_mode).toBe('rebuild');

  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toContainText(/Environment lost|Environnement perdu/, { timeout: 15_000 });
  await card.getByTestId('scenario-rebuild-btn').click();

  // A new terminal, not the deleted one.
  await page.waitForURL(
    (url) => url.pathname.includes('/terminal-session/') && !url.pathname.includes(terminalId),
    { timeout: 300_000 }
  );

  // Same step, and the same flag re-planted on the new machine.
  await submitFlagAndFinish(page, flagBefore);
});
