import { test, expect } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenarioById,
  getAvailableScenario,
  getMyScenarioSessions,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { adminSession } from './helpers/freshUsers';
import { readTerminalText, typeInTerminal, waitForLiveTerminal } from './helpers/xterm';

// ---------------------------------------------------------------------------
// Tier B — challenge mode provisions the WHOLE challenge up front.
//
// A standard scenario deploys each flag as the learner reaches its step. A
// crash_traps scenario cannot: its traps destroy and rebuild the container, so
// there is no later moment to deploy into. Everything therefore ships at launch
// in /tmp/challenge_config.json, which setup.sh reads.
//
// That is exactly what this checks: at the FIRST interactive moment, before a
// single step is completed, both flags are already in the container. Nothing is
// solved here — the run is abandoned right after.
// ---------------------------------------------------------------------------

const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E challenge ${RUN_STAMP}`;
const CONFIG_PATH = '/tmp/challenge_config.json';

let admin: ApiSession | null = null;
let learner: ApiSession;
let scenarioId: string | null = null;
let launchable = false;
let blockReason = '';

test.beforeAll(async () => {
  admin = await adminSession();
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  if (!admin) return;

  const scenario = await importScenario(admin, null, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-challenge.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    crash_traps: true,
    steps: [
      { title: 'Read the rules', step_type: 'info', text_content: 'Two flags are hidden.' },
      { title: 'First flag', step_type: 'flag', has_flag: true, text_content: 'Find it.' },
      { title: 'Second flag', step_type: 'flag', has_flag: true, text_content: 'Find it too.' },
    ],
  });
  scenarioId = scenario.id;

  const card = await getAvailableScenario(learner, FIXTURE_TITLE);
  launchable = !!card?.launchable;
  blockReason = card?.block_reason || '';
});

test.afterAll(async () => {
  if (scenarioId) {
    await cleanupScenarioSession(learner, scenarioId).catch(() => {});
    if (admin) await deleteScenarioById(admin, scenarioId);
  }
  await admin?.api.dispose();
  await learner?.api.dispose();
});

test('a challenge ships every flag into the container before the first step is solved', async ({
  page,
}) => {
  test.skip(!admin, 'no platform admin to import the fixture — set E2E_ADMIN_EMAIL / E2E_ADMIN_PASSWORD');
  test.skip(
    !launchable,
    `fixture not launchable (${blockReason}) — Tier B needs a live tt-backend + Incus with an apk distribution`
  );
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    test.skip(true, 'launch refused by the backend (likely host capacity)');
  }

  // Still on the opening info step: nothing has been solved.
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the rules', {
    timeout: 60_000,
  });
  await waitForLiveTerminal(page);

  // What a challenger does first — and the count is read back separately
  // because a long JSON line wraps in the xterm buffer and could split a token.
  await typeInTerminal(page, `cat ${CONFIG_PATH}`);
  await expect
    .poll(
      async () => {
        await typeInTerminal(page, `echo "flags=$(grep -c 'FLAG{' ${CONFIG_PATH})"`);
        await page.waitForTimeout(1_500);
        return Number((await readTerminalText(page)).match(/flags=(\d+)/)?.[1] ?? -1);
      },
      { timeout: 60_000 }
    )
    .toBe(2);

  const sessions = await getMyScenarioSessions(learner);
  const session = sessions.find((s: any) => s.scenario_id === scenarioId);
  expect(session, 'the learner should own a session for the challenge').toBeTruthy();
  expect(session.current_step, 'no step has been solved yet').toBe(0);

  await page.getByTestId('scenario-abandon-btn').click();
  await page.locator('.el-message-box__btns .el-button--primary').click();
});
