import { test, expect } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  findOwnedTeamOrgId,
  importScenario,
  deleteScenario,
  getAvailableScenario,
  getMyScenarioSessions,
  getTerminalSession,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { readTerminalText, typeInTerminal, waitForLiveTerminal } from './helpers/xterm';

// ---------------------------------------------------------------------------
// Tier B — challenge mode provisions the WHOLE challenge up front.
//
// A standard scenario deploys each flag as the learner reaches its step. A
// crash_traps scenario cannot: its traps destroy and rebuild the container, so
// there is no later moment to deploy into. Everything therefore ships at launch
// in /tmp/challenge_config.json, which setup.sh reads.
//
// That is exactly what this checks: at the FIRST interactive moment, before a
// single step is completed, both flags are already in the container. Nothing is
// solved here — the run is abandoned right after.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_TRAINER_EMAIL || 'marc@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E challenge ${RUN_STAMP}`;
const CONFIG_PATH = '/tmp/challenge_config.json';

let trainer: ApiSession;
let learner: ApiSession;
let orgId: string | null = null;
let scenarioId: string | null = null;
let launchable = false;

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  orgId = await findOwnedTeamOrgId(trainer);
  if (!orgId) return;

  const scenario = await importScenario(trainer, orgId, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-challenge.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    crash_traps: true,
    steps: [
      { title: 'Read the rules', step_type: 'info', text_content: 'Two flags are hidden.' },
      { title: 'First flag', step_type: 'flag', has_flag: true, text_content: 'Find it.' },
      { title: 'Second flag', step_type: 'flag', has_flag: true, text_content: 'Find it too.' },
    ],
  });
  scenarioId = scenario.id;

  launchable = !!(await getAvailableScenario(learner, FIXTURE_TITLE))?.launchable;
});

test.afterAll(async () => {
  if (scenarioId) {
    await cleanupScenarioSession(learner, scenarioId).catch(() => {});
    if (orgId) await deleteScenario(trainer, orgId, scenarioId);
  }
  await trainer?.api.dispose();
  await learner?.api.dispose();
});

test('a challenge ships every flag into the container before the first step is solved', async ({
  page,
}) => {
  test.skip(!orgId, `trainer ${TRAINER_EMAIL} owns no team org — seed the dev personas first`);
  test.skip(
    !launchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    test.skip(true, 'launch refused by the backend (likely host capacity)');
  }

  // Still on the opening info step: nothing has been solved.
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the rules', {
    timeout: 60_000,
  });
  await waitForLiveTerminal(page);

  // What a challenger does first — and the count is read back separately
  // because a long JSON line wraps in the xterm buffer and could split a token.
  await typeInTerminal(page, `cat ${CONFIG_PATH}`);
  await expect
    .poll(
      async () => {
        await typeInTerminal(page, `echo "flags=$(grep -c 'FLAG{' ${CONFIG_PATH})"`);
        await page.waitForTimeout(1_500);
        return Number((await readTerminalText(page)).match(/flags=(\d+)/)?.[1] ?? -1);
      },
      { timeout: 60_000 }
    )
    .toBe(2);

  const sessions = await getMyScenarioSessions(learner);
  const session = sessions.find((s: any) => s.scenario_id === scenarioId);
  expect(session, 'the learner should own a session for the challenge').toBeTruthy();
  expect(session.current_step, 'no step has been solved yet').toBe(0);

  // Traps rebuild the container, so a challenge terminal must never persist.
  // Best-effort: older backends do not report the mode at all.
  const terminal = await getTerminalSession(learner, session.terminal_session_id);
  if (terminal?.persistence_mode) {
    expect(terminal.persistence_mode).toBe('ephemeral');
  }

  await page.getByTestId('scenario-abandon-btn').click();
  await page.locator('.el-message-box__btns .el-button--primary').click();
});
