import { test, expect, type Page } from '@playwright/test';
import { loginFresh } from './helpers/auth';
import { addStep, fillStepAndSave, outlineTitles } from './helpers/scenarioEditor';

// ---------------------------------------------------------------------------
// Smoke E2E for the scenario editor — locks in the author flow
// against future regressions.
//
// Author: an org manager (Nadia / ESITECH) creates a scenario, adds info /
// quiz / flag steps from the outline, titles and saves each one, reloads,
// asserts the outline lists them in order, then deletes the scenario.
//
// What is intentionally NOT covered here:
//  - terminal step (would require provisioning a real container)
//  - "Play as student" walkthrough
//  - email-based flows (verification, invites)
//
// See test.skip below for the deferred scenarios.
// ---------------------------------------------------------------------------

const TEST_PASSWORD = 'OcfTest2026!';
const ORG_MANAGER_EMAIL = 'nadia@test.ocf';

// ---------------------------------------------------------------------------
// Helper: dismiss the email verification banner if visible
// ---------------------------------------------------------------------------
async function dismissVerificationBanner(page: Page) {
  const dismissBtn = page.locator('.verification-banner .btn-dismiss');
  if (await dismissBtn.isVisible({ timeout: 2_000 }).catch(() => false)) {
    await dismissBtn.click({ force: true });
    await page.waitForTimeout(300);
  }
}

// ---------------------------------------------------------------------------
// Helper: navigate to /scenario-editor and wait for the editor shell
// ---------------------------------------------------------------------------
async function gotoScenarioEditor(page: Page) {
  await page.goto('/scenario-editor');
  await dismissVerificationBanner(page);
  await page.waitForSelector('[data-testid="scenario-picker"]', { timeout: 15_000 });
}

// ---------------------------------------------------------------------------
// Smoke: full create-edit-save-reload-delete flow
// ---------------------------------------------------------------------------
test.describe('Scenario editor — smoke', () => {
  test('author can create, edit, save, reload, and delete a scenario', async ({
    page,
  }) => {
    test.setTimeout(120_000);

    // Unique scenario name so reruns don't collide with leftover data
    const stamp = Date.now();
    const scenarioName = `e2e-smoke-${stamp}`;
    const scenarioTitle = `E2E smoke ${stamp}`;
    const scenarioDescription = 'Auto-generated by scenario-editor-smoke spec.';

    // 1. Login as an org manager so the scope picker has at least one org
    await loginFresh(page, ORG_MANAGER_EMAIL, TEST_PASSWORD);

    // 2. Navigate to the editor
    await gotoScenarioEditor(page);

    // 3. Click "Create a scenario" in the header
    const createBtn = page.getByTestId('scenario-create-btn');
    await expect(createBtn).toBeVisible({ timeout: 10_000 });
    await createBtn.click({ force: true });

    // 4. Fill name + title + description in the scenario edit modal
    const nameInput = page
      .locator('.modal-form input.form-control')
      .first();
    await nameInput.waitFor({ state: 'visible', timeout: 10_000 });
    await nameInput.fill(scenarioName);

    const titleInput = page
      .locator('.modal-form input.form-control')
      .nth(1);
    await titleInput.fill(scenarioTitle);

    const descTextarea = page.locator('.modal-form textarea.form-control').first();
    await descTextarea.fill(scenarioDescription);

    // 5. Select scope: prefer ESITECH if listed, else first org
    const scopeSelect = page.locator('#create-scope');
    await scopeSelect.waitFor({ state: 'visible', timeout: 5_000 });

    const scopeOptions = await scopeSelect.locator('option').allInnerTexts();
    const esitechIdx = scopeOptions.findIndex((label) => /esitech/i.test(label));
    if (esitechIdx >= 0) {
      // selectOption by label match — case-insensitive find requires value
      const esitechValue = await scopeSelect
        .locator('option')
        .nth(esitechIdx)
        .getAttribute('value');
      if (esitechValue) {
        await scopeSelect.selectOption(esitechValue);
      }
    }
    // Otherwise leave the auto-picked default scope (org:<currentOrg>)

    // 6. Save the scenario (BaseModal default-footer Confirm button)
    // The scenario edit modal uses `show-default-footer + confirm-text` so the
    // save button is `.base-modal-footer .btn.btn-primary` — there's only one
    // visible BaseModal at this point.
    const scenarioSaveBtn = page
      .locator('.base-modal-footer .btn.btn-primary')
      .first();
    await scenarioSaveBtn.click({ force: true });

    // Wait for the modal to close — the scope select disappears
    await scopeSelect
      .waitFor({ state: 'hidden', timeout: 15_000 })
      .catch(() => {
        // If modal didn't auto-close, fail loudly below via the next assertion
      });

    // 7. The new scenario opens with no step, then gets three from the outline.
    await expect(page.getByTestId('no-steps-state')).toBeVisible({ timeout: 15_000 });

    const steps: { type: 'info' | 'quiz' | 'flag'; title: string }[] = [
      { type: 'info', title: 'E2E info step' },
      { type: 'quiz', title: 'E2E quiz step' },
      { type: 'flag', title: 'E2E flag step' },
    ];

    for (const step of steps) {
      await addStep(page, step.type);
      await fillStepAndSave(page, step.title);
    }
    await expect(outlineTitles(page)).toHaveText(steps.map((s) => s.title));

    // 8. A reload reopens the same scenario with the same steps, in order.
    await page.reload();
    await dismissVerificationBanner(page);
    await expect(page.getByTestId('scenario-picker').locator('option:checked')).toHaveText(scenarioTitle, { timeout: 15_000 });
    await expect(outlineTitles(page)).toHaveText(steps.map((s) => s.title), { timeout: 15_000 });

    // 9. Delete it from the header's ⋯ menu.
    await page.getByTestId('scenario-more-actions').click();
    await page.getByTestId('scenario-delete').click();
    await page.locator('.base-modal-footer .btn.btn-primary').first().click();

    await expect(page.getByTestId('editor-empty-state')).toBeVisible({ timeout: 10_000 });
    await expect(page.getByTestId('scenario-picker').locator('option', { hasText: scenarioTitle })).toHaveCount(0);
  });

});
