import { test, expect } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  findOwnedTeamOrgId,
  importScenario,
  deleteScenario,
  getAvailableScenario,
  getMyScenarioSessions,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { readFlagFromTerminal, typeInTerminal, waitForLiveTerminal } from './helpers/xterm';

// ---------------------------------------------------------------------------
// Tier B recipe spec — one real end-to-end scenario run, containers included.
//
// marc (trainer, owns marc-corp) imports a 4-step public fixture via the org
// import-json API; karim (learner) then does everything a student does, in
// the real UI: launches from /scenarios, acknowledges the briefing, passes
// the terminal step, reads the HMAC flag with `cat` in the actual xterm,
// answers the quiz, and lands on the completion panel. Grade is asserted
// through the API afterwards (0–100 scale).
//
// Requirements (local only): ocf-core on :8080, vite, tt-backend with a live
// Incus behind it, and an 'apk'-compatible distribution. The spec SELF-SKIPS
// when the fixture is not launchable — in CI (no tt-backend/Incus) it skips
// quietly; the mocked Tier A suite covers the player there.
//
// This spec is the recipe: copy its structure for the other Tier B specs.
// Demo mode: DEMO=1 npx playwright test scenario-run
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_TRAINER_EMAIL || 'marc@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E linear run ${RUN_STAMP}`;

let trainer: ApiSession;
let learner: ApiSession;
let orgId: string | null = null;
let scenarioId: string | null = null;
let launchable = false;

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  orgId = await findOwnedTeamOrgId(trainer);
  if (!orgId) return;

  const scenario = await importScenario(trainer, orgId, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-run.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    intro_text: 'Welcome to the E2E fixture scenario.',
    finish_text: 'Well done, fixture complete.',
    steps: [
      { title: 'Read the briefing', step_type: 'info', text_content: 'Just read and continue.' },
      {
        title: 'Touch a file',
        step_type: 'terminal',
        text_content: 'Run `touch /tmp/e2e-marker` in the terminal.',
        // no verify_script: an empty script auto-passes on Verify
      },
      {
        title: 'Capture the flag',
        step_type: 'flag',
        has_flag: true,
        text_content: 'The flag hides in /tmp — cat it and submit.',
      },
      {
        title: 'Final quiz',
        step_type: 'quiz',
        show_immediate_feedback: true,
        questions: [
          {
            order: 1,
            question_text: 'Does `ls` list files?',
            question_type: 'true_false',
            correct_answer: 'true',
            points: 1,
          },
        ],
      },
    ],
  });
  scenarioId = scenario.id;

  const card = await getAvailableScenario(learner, FIXTURE_TITLE);
  launchable = !!card?.launchable;
});

test.afterAll(async () => {
  if (scenarioId) {
    await cleanupScenarioSession(learner, scenarioId).catch(() => {});
    if (orgId) await deleteScenario(trainer, orgId, scenarioId);
  }
  await trainer?.api.dispose();
  await learner?.api.dispose();
});

test('learner launches, follows and completes a real scenario', async ({ page }) => {
  test.skip(!orgId, `trainer ${TRAINER_EMAIL} owns no team org — seed the dev personas first`);
  test.skip(
    !launchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  // Terminal creation + step transitions are real: give the whole journey room.
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  // Find our fixture card and launch it
  const card = page.getByTestId('scenario-card').filter({ hasText: FIXTURE_TITLE });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  // Real terminal provisioning — the overlay may or may not flash by; what
  // matters is landing in the player with the first step up. A busy host can
  // refuse the launch outright (503 "Server at capacity") — that is an
  // environment condition, not a product defect: skip instead of failing.
  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    const toastText = (await errorToast.innerText().catch(() => '')) || 'launch refused';
    test.skip(true, `launch refused by the backend (likely host capacity): ${toastText.slice(0, 120)}`);
  }
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the briefing', {
    timeout: 60_000,
  });

  // Step 1 — info: acknowledge
  await page.getByTestId('scenario-info-ack').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Touch a file', {
    timeout: 30_000,
  });

  // Step 2 — terminal: do the actual work in the actual container, then verify
  await waitForLiveTerminal(page);
  await typeInTerminal(page, 'touch /tmp/e2e-marker');
  await page.getByTestId('scenario-verify-btn').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', {
    timeout: 30_000,
  });

  // Step 3 — flag: read the per-session HMAC flag from the container the way
  // a student does, then submit it. The deploy path is /tmp/.flag_step_<order>;
  // read the live step order from the API rather than assuming 0- or 1-based.
  const mine = await getMyScenarioSessions(learner);
  const session = mine.find((s) => s.scenario_id === scenarioId);
  expect(session, 'learner should have a scenario session by now').toBeTruthy();
  const flag = await readFlagFromTerminal(page, session!.current_step);
  await page.getByTestId('scenario-flag-input').fill(flag);
  await page.getByTestId('scenario-flag-submit').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Final quiz', {
    timeout: 30_000,
  });

  // Step 4 — quiz: answer "true", submit, finish
  await page.getByTestId('quiz-option').filter({ hasText: /vrai|true/i }).first().click();
  await page.getByTestId('quiz-submit').click();
  await expect(page.getByTestId('quiz-results-score')).toBeVisible({ timeout: 15_000 });
  await page.getByTestId('quiz-finish').click();

  // Completion panel, then the API-visible outcome: completed, grade 100
  await expect(page.getByTestId('scenario-completed')).toBeVisible({ timeout: 30_000 });
  await expect
    .poll(
      async () => {
        const sessions = await getMyScenarioSessions(learner);
        const s = sessions.find((x) => x.scenario_id === scenarioId);
        return s && { status: s.status, grade: s.grade };
      },
      { timeout: 20_000 }
    )
    .toEqual({ status: 'completed', grade: 100 });

  // Aftermath — history: the run shows up on /my-scenarios via real navigation
  await navigateViaMenuCategory(page, 'scenarios', '/my-scenarios');
  await expect(page.locator('body')).toContainText(FIXTURE_TITLE, { timeout: 15_000 });
});
