import { test, expect, type Page } from '@playwright/test';
import { loginFresh } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenario,
  archiveScenario,
  unarchiveScenario,
  organizationDisplayName,
  findTeacherGroup,
  type ApiSession,
} from './helpers/scenarioApi';

// ---------------------------------------------------------------------------
// Archiving — retiring a scenario whose results must stay readable.
//
// Deleting a scenario removes its assignments and leaves past class results
// without the scenario they were earned on. Archiving keeps the row: it stops
// the scenario being offered, assignable and launchable, and nothing else.
//
// Two guarantees, read off the real pages:
//
//  1. The learner's catalogue drops an archived scenario and gets it back on
//     restore — the visibility half, driven through the API so the state
//     change is unambiguous.
//  2. The trainer can do it from the library without leaving the page, and an
//     archived scenario stays reachable there behind the "show archived"
//     toggle — the curation half, driven entirely through the UI.
//
// Neither test provisions a container, so both run on a busy host.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_ORG_MANAGER_EMAIL || 'nadia@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const CATALOGUE_TITLE = `E2E archive catalogue ${RUN_STAMP}`;
const LIBRARY_TITLE = `E2E archive library ${RUN_STAMP}`;

let trainer: ApiSession;
let learner: ApiSession;
let orgId: string | null = null;
let orgName = '';
let catalogueScenarioId: string | null = null;
let libraryScenarioId: string | null = null;

/** The learner's launcher card for a title, however many other cards are up. */
function scenarioCard(page: Page, title: string) {
  return page.getByTestId('scenario-card').filter({ hasText: title });
}

/**
 * Re-enter the launcher the way a learner would after doing something else, so
 * the page refetches its scenario list. Specs never page.goto() inside the
 * product, and a reload would not show WHERE the user went.
 */
async function revisitLauncher(page: Page): Promise<void> {
  await navigateViaMenuCategory(page, 'scenarios', '/my-scenarios');
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
}

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);

  const group = await findTeacherGroup(trainer, /test class/i, 1);
  if (!group) return;
  orgId = group.organization_id;
  orgName = await organizationDisplayName(trainer, orgId!);

  // Public: the learner sees it without an assignment, so this test isolates
  // archiving from the assignment window (covered in scenario-assignment.spec).
  const catalogue = await importScenario(trainer, orgId!, {
    title: CATALOGUE_TITLE,
    description: 'Auto-generated by scenario-archive.spec.ts — safe to delete.',
    is_public: true,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  catalogueScenarioId = catalogue.id;

  const library = await importScenario(trainer, orgId!, {
    title: LIBRARY_TITLE,
    description: 'Auto-generated by scenario-archive.spec.ts — safe to delete.',
    is_public: false,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  libraryScenarioId = library.id;
});

test.afterAll(async () => {
  if (orgId) {
    if (catalogueScenarioId) await deleteScenario(trainer, orgId, catalogueScenarioId);
    if (libraryScenarioId) await deleteScenario(trainer, orgId, libraryScenarioId);
  }
  await trainer?.api.dispose();
  await learner?.api.dispose();
});

test('archiving takes a scenario out of the learner catalogue, restoring puts it back', async ({
  page,
}) => {
  test.skip(!orgId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.setTimeout(120_000);

  await loginFresh(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  await expect(
    scenarioCard(page, CATALOGUE_TITLE),
    'a public scenario is offered before it is archived'
  ).toBeVisible({ timeout: 15_000 });

  await archiveScenario(trainer, catalogueScenarioId!);

  await revisitLauncher(page);
  await expect(
    scenarioCard(page, CATALOGUE_TITLE),
    'an archived scenario must no longer be offered, public or not'
  ).toHaveCount(0);

  await unarchiveScenario(trainer, catalogueScenarioId!);

  await revisitLauncher(page);
  await expect(
    scenarioCard(page, CATALOGUE_TITLE),
    'restoring puts the scenario back in service'
  ).toBeVisible({ timeout: 15_000 });
});

test('a trainer archives from the library and can still find it there', async ({ page }) => {
  test.skip(!orgId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.setTimeout(120_000);

  await loginFresh(page, TRAINER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'organizations', '/organizations');

  // Targeted by icon rather than label: the UI runs in French here, and
  // "Gérer" / "Scénarios" do not match an unaccented pattern.
  await page
    .locator('.organization-card')
    .filter({ hasText: orgName })
    .first()
    .locator('button:has(i.fa-cog)')
    .click();
  await page.getByRole('tab').filter({ hasText: /sc.nario/i }).click();

  const card = page.locator('.scenario-card').filter({ hasText: LIBRARY_TITLE });
  await expect(card, 'the library lists the scenario').toBeVisible({ timeout: 15_000 });

  // By icon, not label: the library also carries an "Export KillerCoda
  // Archive" button, whose name matches any pattern loose enough to survive
  // the FR/EN switch.
  await card.locator('button:has(i.fa-box-archive)').click();

  // Archiving retires the scenario for the whole organization, so it confirms.
  await page.locator('.base-modal-footer .btn-primary').click();

  await expect(
    page.locator('.scenario-card').filter({ hasText: LIBRARY_TITLE }),
    'an archived scenario leaves the default library view'
  ).toHaveCount(0, { timeout: 15_000 });

  await page.locator('.ocf-archived-toggle input').check();

  const archived = page.locator('.scenario-card').filter({ hasText: LIBRARY_TITLE });
  await expect(archived, 'and comes back once archived ones are shown').toBeVisible();
  await expect(
    archived.locator('.ocf-archived-badge'),
    'badged, so it is not mistaken for an active scenario'
  ).toBeVisible();
  await expect(
    archived.locator('button:has(i.fa-rotate-left)'),
    'and offers Restore in place of Archive'
  ).toBeVisible();
  await expect(
    archived.locator('button:has(i.fa-box-archive)'),
    'Archive is gone while it is archived'
  ).toHaveCount(0);
});
