import { test, expect, type Page } from '@playwright/test';
import { login, loginFresh, switchToOrg } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  findOwnedTeamOrg,
  findTeacherGroup,
  importScenario,
  deleteScenario,
  createGroupAssignment,
  deleteAssignment,
  getGroupScenarioResults,
  getMyScenarioSessions,
  launchScenarioSession,
  cleanupScenarioSession,
  ensureOrgMembership,
  removeOrgMembership,
  getUserId,
  type ApiSession,
} from './helpers/scenarioApi';

// ---------------------------------------------------------------------------
// Tier B — the trainer's side of a scenario, with real containers.
//
// marc owns marc-corp and teaches a class with two learners. This spec walks
// the three things he does that a learner never does: rehearse the scenario
// himself, start it for the whole class at once, and wipe the attempts.
//
// The tests run serially and build on each other: bulk start puts sessions on
// the wall, the wall test reads them, the reset test clears them.
//
// Where the preview button actually lives: NOT on /classes/:id/scenarios (that
// page only lists assignments) but in the scenario editor header — "Play as
// learner", which POSTs /scenarios/:id/preview and opens the player in a new
// tab. The preview session carries IsPreview, which is why it must not surface
// in the class results.
//
// Fixture precondition, and a product gap behind it: bulk start resolves each
// member's plan against the SCENARIO's organization, but adding someone to a
// class does NOT make them a member of the org that class belongs to. The
// seeded learners are in marc's class without being in marc-corp, so bulk start
// answers "failed to resolve subscription plan" for every one of them. The
// setup below puts that right for the duration of the run and takes it back
// out afterwards; the gap itself is reported, not worked around silently.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_TRAINER_EMAIL || 'marc@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const SECOND_LEARNER_EMAIL = process.env.E2E_USER_2 || 'jp@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FIXTURE_TITLE = `E2E teacher ${RUN_STAMP}`;

let trainer: ApiSession;
let learner: ApiSession;
let secondLearner: ApiSession;
let orgId: string | null = null;
let orgDisplayName = '';
let groupId: string | null = null;
let learnerCount = 0;
let scenarioId: string | null = null;
let assignmentId: string | null = null;
let grantedMemberships: string[] = [];
/** How many learner sessions are live — the wall must show exactly that many tiles. */
let startedCount = 0;

test.describe.configure({ mode: 'serial' });

/**
 * Sign in and put the console in the org that owns the class. My Classes is
 * org-scoped: in another org context it truthfully reports "you manage no class
 * here", so the switch is part of the journey, not test plumbing.
 */
async function openClassConsole(page: Page): Promise<void> {
  await loginFresh(page, TRAINER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await switchToOrg(page, orgDisplayName);
  await page.locator('.main-menu .my-classes-header').click();
}

/**
 * The class row for our fixture — two dev classes share a display name, and the
 * assignment chip is what tells them apart on the console.
 */
function fixtureClassRow(page: Page) {
  return page.locator('[data-test="class-row"]').filter({ hasText: FIXTURE_TITLE });
}

async function openFixtureClassScenarios(page: Page): Promise<void> {
  await openClassConsole(page);
  const classRow = fixtureClassRow(page);
  await expect(classRow).toBeVisible({ timeout: 20_000 });
  await classRow.click();
  await page.locator('.class-nav a[href$="/scenarios"]').click();
}

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  secondLearner = await apiLogin(SECOND_LEARNER_EMAIL, PASSWORD);

  const org = await findOwnedTeamOrg(trainer);
  const group = await findTeacherGroup(trainer, /docker fondamentaux/i, 2);
  if (!org || !group) return;
  orgId = org.id;
  orgDisplayName = org.displayName;
  groupId = group.group_id;
  learnerCount = group.learner_count;

  for (const who of [learner, secondLearner]) {
    const membershipId = await ensureOrgMembership(trainer, orgId, await getUserId(who));
    if (membershipId) grantedMemberships.push(membershipId);
  }

  const scenario = await importScenario(trainer, orgId, {
    title: FIXTURE_TITLE,
    description: 'Auto-generated by scenario-teacher.spec.ts — safe to delete.',
    is_public: false,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  scenarioId = scenario.id;

  const assignment = await createGroupAssignment(trainer, scenarioId, groupId);
  assignmentId = assignment.id;
});

test.afterAll(async () => {
  if (scenarioId) {
    for (const who of [trainer, learner, secondLearner]) {
      await cleanupScenarioSession(who, scenarioId).catch(() => {});
    }
  }
  if (assignmentId) await deleteAssignment(trainer, assignmentId);
  if (orgId && scenarioId) await deleteScenario(trainer, orgId, scenarioId);
  for (const membershipId of grantedMemberships) await removeOrgMembership(trainer, membershipId);
  await trainer?.api.dispose();
  await learner?.api.dispose();
  await secondLearner?.api.dispose();
});

test('the trainer rehearsal opens a session the class results do not count', async ({
  page,
  context,
}) => {
  test.skip(!groupId, `${TRAINER_EMAIL} teaches no class with learners — seed the dev personas first`);
  test.setTimeout(360_000);

  // Remember me, because the preview opens its own tab: without it the token
  // sits in sessionStorage and the new tab shows the LOGIN page instead of the
  // player. That is a live product defect, reported separately — the flag here
  // is what lets this test reach the behaviour it is actually about.
  await login(page, TRAINER_EMAIL, PASSWORD, { rememberMe: true });
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'terminals', '/scenario-editor');

  const selector = page.locator('.scenario-select');
  await expect(selector).toBeVisible({ timeout: 20_000 });
  await expect
    .poll(async () => selector.locator(`option[value="${scenarioId}"]`).count(), { timeout: 20_000 })
    .toBe(1);
  await selector.selectOption(scenarioId!);

  const previewBtn = page.locator('.editor-header button.btn-icon:has(i.fa-play)');
  await expect(previewBtn).toBeVisible({ timeout: 20_000 });
  await previewBtn.click();
  await page.locator('.base-modal-footer .btn.btn-primary').first().click();

  // The preview deliberately opens in its own tab so the author keeps the
  // canvas. A host with no room refuses the launch instead — skip, don't fail.
  const previewTab = await Promise.race([
    context.waitForEvent('page', { timeout: 240_000 }),
    page
      .locator('.el-notification')
      .waitFor({ state: 'visible', timeout: 240_000 })
      .then(() => null),
  ]);
  if (!previewTab) {
    test.skip(true, 'preview refused by the backend (likely host capacity)');
  }
  await previewTab!.waitForLoadState();
  await expect(previewTab!.getByTestId('scenario-step-title')).toBeVisible({ timeout: 120_000 });

  const trainerSessions = await getMyScenarioSessions(trainer);
  expect(
    trainerSessions.some((s) => s.scenario_id === scenarioId),
    'the trainer should own a session after previewing'
  ).toBe(true);

  const results = await getGroupScenarioResults(trainer, groupId!, scenarioId!);
  expect(results, 'a rehearsal is not a learner attempt').toEqual([]);

  // Hand the next test a clean slate: a live session on this scenario would
  // make the bulk start replace it rather than create one.
  await cleanupScenarioSession(trainer, scenarioId!);
});

test('bulk start gives every learner in the class a session of their own', async ({ page }) => {
  // BLOCKED on a product defect, not on the environment: BulkStartScenarioModal
  // sends the distribution PREFIX (`alp-s`) where tt-backend's POST /1.0/sessions
  // expects the NAME (`alpine-s`), so every bulk start answers
  //   404 distribution 'alp-s' not found
  // and creates nothing, for every image in the catalog. The test below is the
  // one that should pass once the modal sends `dist.name`; until then it would
  // only pin the breakage.
  test.fixme(true, "bulk start posts the distribution prefix instead of its name — tt-backend 404s");
  test.setTimeout(600_000);

  await openFixtureClassScenarios(page);
  const assignmentCard = page.locator('.assignment-card').filter({ hasText: FIXTURE_TITLE });
  await expect(assignmentCard).toBeVisible({ timeout: 20_000 });

  await assignmentCard.locator('.dropdown-trigger').click();
  await assignmentCard.locator('[data-test="action-bulk-start"]').click();

  // The fixture is an apk scenario, so the teacher picks an Alpine image —
  // the catalog also carries images the scenario cannot run on.
  const distributionSelect = page.locator('.base-modal-container select.form-control');
  await expect(distributionSelect).toBeVisible({ timeout: 20_000 });
  const alpineValue = await distributionSelect
    .locator('option')
    .evaluateAll(
      (options) =>
        (options as HTMLOptionElement[]).find((o) => /alpine/i.test(o.textContent || ''))?.value ?? ''
    );
  expect(alpineValue, 'the backend must offer an Alpine image').not.toBe('');
  await distributionSelect.selectOption(alpineValue);
  await page.locator('.base-modal-footer .btn.btn-primary').first().click();

  // Provisioning one container per member — the result modal is the teacher's
  // own confirmation that the batch landed.
  const resultMessage = page.locator('.result-message');
  await expect(resultMessage).toBeVisible({ timeout: 480_000 });
  startedCount = Number((await resultMessage.innerText()).match(/\d+/)?.[0] ?? 0);
  expect(startedCount, 'the batch must have started something').toBeGreaterThanOrEqual(learnerCount);

  // Each learner is asked for their OWN sessions, so the batch cannot be
  // satisfied by several sessions belonging to the same person.
  for (const [who, email] of [
    [learner, LEARNER_EMAIL],
    [secondLearner, SECOND_LEARNER_EMAIL],
  ] as const) {
    await expect
      .poll(
        async () => (await getMyScenarioSessions(who)).some((s: any) => s.scenario_id === scenarioId),
        { timeout: 60_000 }
      )
      .toBe(true);
  }

  const results = await getGroupScenarioResults(trainer, groupId!, scenarioId!);
  expect(results.length, 'the class results must carry the whole batch').toBe(startedCount);
});

test('the live wall shows one tile per learner at work and nothing else', async ({ page }) => {
  test.skip(!groupId, `${TRAINER_EMAIL} teaches no class with learners — seed the dev personas first`);
  test.setTimeout(600_000);

  // The learners are put to work through the launch API rather than the bulk
  // start above, which is broken: what this test is about is the wall, and it
  // needs live sessions from wherever they legitimately come.
  for (const who of [learner, secondLearner]) {
    if (await launchScenarioSession(who, scenarioId!, orgId!)) startedCount += 1;
  }
  test.skip(startedCount === 0, 'no learner session could be provisioned — likely host capacity');

  await openClassConsole(page);
  const classRow = fixtureClassRow(page);
  await expect(classRow).toBeVisible({ timeout: 20_000 });
  await classRow.click();

  await page.getByRole('tab', { name: /mur|wall/i }).click();
  const tiles = page.locator('.live-sessions-tile');
  await expect(tiles).toHaveCount(startedCount, { timeout: 60_000 });

  const labels = await tiles.evaluateAll((els) => els.map((el) => el.getAttribute('aria-label') || ''));
  expect(new Set(labels).size, 'one tile per person, not several for the same one').toBe(startedCount);
});

test('teacher reset abandons the sessions the learners had in flight', async ({ page }) => {
  test.skip(!groupId, `${TRAINER_EMAIL} teaches no class with learners — seed the dev personas first`);
  test.skip(startedCount === 0, 'no learner session was provisioned, so there is nothing to reset');
  test.setTimeout(180_000);

  await openFixtureClassScenarios(page);
  const assignmentCard = page.locator('.assignment-card').filter({ hasText: FIXTURE_TITLE });
  await expect(assignmentCard).toBeVisible({ timeout: 20_000 });
  await assignmentCard.locator('.dropdown-trigger').click();
  await assignmentCard.locator('[data-test="action-reset"]').click();
  await page.locator('.base-modal-footer .btn.btn-primary').first().click();

  await expect
    .poll(
      async () => {
        const sessions = await getMyScenarioSessions(learner);
        return sessions.find((s: any) => s.scenario_id === scenarioId)?.status;
      },
      { timeout: 60_000 }
    )
    .toBe('abandoned');
});
