import { test, expect, type Page } from '@playwright/test';
import { loginFresh } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenario,
  archiveScenario,
  findTeacherGroup,
  type ApiSession,
} from './helpers/scenarioApi';

// ---------------------------------------------------------------------------
// The scenario editor lists no archived scenario.
//
// Restoring is the org Scenarios tab's and the admin list's job, so the
// editor has nothing to do with an archived scenario:
//
//  1. archiving the open scenario from the ⋯ menu closes it — back to the
//     empty state, the toast says it worked, and the picker no longer offers it;
//  2. a link to a scenario archived meanwhile (a colleague did it, the tab was
//     left open) says so instead of opening a blank editor.
//
// Neither test provisions a container.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_ORG_MANAGER_EMAIL || 'nadia@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const MENU_TITLE = `E2E editor archive menu ${RUN_STAMP}`;
const LINK_TITLE = `E2E editor archive link ${RUN_STAMP}`;

let trainer: ApiSession;
let orgId: string | null = null;
const scenarioIds: string[] = [];

test.describe.configure({ mode: 'serial' });

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  orgId = (await findTeacherGroup(trainer, /test class/i, 1))?.organization_id ?? null;
  if (!orgId) return;
  for (const title of [MENU_TITLE, LINK_TITLE]) {
    const scenario = await importScenario(trainer, orgId, {
      title,
      description: 'Auto-generated by scenario-editor-archive.spec.ts — safe to delete.',
      is_public: false,
      steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
    });
    scenarioIds.push(scenario.id);
  }
});

test.afterAll(async () => {
  if (orgId) for (const id of scenarioIds) await deleteScenario(trainer, orgId, id);
  await trainer?.api.dispose();
});

async function openEditorOn(page: Page, title: string): Promise<void> {
  await loginFresh(page, TRAINER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await navigateViaMenuCategory(page, 'scenarios', '/scenario-editor');
  const picker = page.getByTestId('scenario-picker');
  await expect(picker.locator('option', { hasText: title })).toHaveCount(1, { timeout: 20_000 });
  await picker.selectOption({ label: title });
  await expect(page.getByTestId('editor-empty-state')).toHaveCount(0, { timeout: 15_000 });
}

test('archiving the open scenario closes it and drops it from the picker', async ({ page }) => {
  test.skip(!orgId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.setTimeout(120_000);
  await openEditorOn(page, MENU_TITLE);

  await page.getByTestId('scenario-more-actions').click();
  await page.locator('.ocf-header-menu-item:has(i.fa-box-archive)').click();
  await expect(
    page.locator('.ocf-header-menu-item:has(i.fa-rotate-left)'),
    'the editor offers no Restore: it never shows an archived scenario'
  ).toHaveCount(0);
  await page.locator('.base-modal-footer .btn-primary').click();

  await expect(page.locator('.el-notification'), 'the toast says it worked').toBeVisible();
  await expect(page.getByTestId('editor-empty-state'), 'and the editor is back to empty').toBeVisible({ timeout: 15_000 });
  await expect(page.getByTestId('editor-archived-notice')).toHaveCount(0);
  await expect(
    page.getByTestId('scenario-picker').locator('option', { hasText: MENU_TITLE }),
    'the picker no longer offers it'
  ).toHaveCount(0);
});

test('a link to a scenario archived meanwhile says so', async ({ page }) => {
  test.skip(!orgId, `${TRAINER_EMAIL} teaches no populated class — seed the dev personas first`);
  test.setTimeout(120_000);
  await openEditorOn(page, LINK_TITLE);
  expect(new URL(page.url()).searchParams.get('scenarioId')).toBe(scenarioIds[1]);

  // A colleague archives it while the tab is open; the author comes back to it.
  await archiveScenario(trainer, scenarioIds[1]);
  await page.reload();

  const empty = page.getByTestId('editor-empty-state');
  await expect(empty).toBeVisible({ timeout: 20_000 });
  await expect(empty.getByTestId('editor-archived-notice')).toHaveText(/archiv/i);
  await expect(page.getByTestId('scenario-picker').locator('option', { hasText: LINK_TITLE })).toHaveCount(0);
});
