import { test, expect, type Page } from '@playwright/test';
import { login } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  findOwnedTeamOrgId,
  importScenario,
  deleteScenario,
  getAvailableScenario,
  getMyScenarioSessions,
  cleanupScenarioSession,
  type ApiSession,
} from './helpers/scenarioApi';
import { typeInTerminal, waitForLiveTerminal } from './helpers/xterm';

// ---------------------------------------------------------------------------
// Tier B — the two ways a learner leaves a step, both against a real container.
//
//  1. A verify_script genuinely gates: `test -f /tmp/e2e-ok` fails until the
//     learner creates the file, and a failed check leaves them where they were.
//     (An absent verify_script auto-passes — that path is the recipe spec's.)
//  2. Abandoning ends the run, and the learner's own history says so.
//
// Two fixtures rather than one, because a scenario admits a single active
// session per learner and abandoning the first would spoil the verify test.
// ---------------------------------------------------------------------------

const TRAINER_EMAIL = process.env.E2E_TRAINER_EMAIL || 'marc@test.ocf';
const LEARNER_EMAIL = process.env.E2E_USER || 'karim@test.ocf';
const PASSWORD = process.env.E2E_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const GATED_TITLE = `E2E verify gate ${RUN_STAMP}`;
const ABANDON_TITLE = `E2E abandon ${RUN_STAMP}`;
const GATED_STEP = 'Create the marker file';

let trainer: ApiSession;
let learner: ApiSession;
let orgId: string | null = null;
let gatedScenarioId: string | null = null;
let abandonScenarioId: string | null = null;
let launchable = false;

/**
 * Launch a fixture from the launcher page and land in the player. Returns false
 * when the host refuses the launch (an error toast instead of navigation) —
 * that is capacity, not a product defect, so callers skip.
 */
async function launchFromLauncher(page: Page, title: string): Promise<boolean> {
  await navigateViaMenuCategory(page, 'terminals', '/scenarios');
  const card = page.getByTestId('scenario-card').filter({ hasText: title });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  return /\/terminal-session\//.test(page.url());
}

test.beforeAll(async () => {
  trainer = await apiLogin(TRAINER_EMAIL, PASSWORD);
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  orgId = await findOwnedTeamOrgId(trainer);
  if (!orgId) return;

  const gated = await importScenario(trainer, orgId, {
    title: GATED_TITLE,
    description: 'Auto-generated by scenario-verify-fail.spec.ts — safe to delete.',
    is_public: true,
    steps: [
      {
        title: GATED_STEP,
        step_type: 'terminal',
        text_content: 'Run `touch /tmp/e2e-ok`, then verify.',
        // Echoes on failure: a bare `test -f` exits 1 with empty stdout, and the
        // player then shows "failed" with nothing for the learner to act on.
        verify_script: 'test -f /tmp/e2e-ok || { echo "/tmp/e2e-ok is missing"; exit 1; }',
      },
    ],
  });
  gatedScenarioId = gated.id;

  const abandonable = await importScenario(trainer, orgId, {
    title: ABANDON_TITLE,
    description: 'Auto-generated by scenario-verify-fail.spec.ts — safe to delete.',
    is_public: true,
    steps: [{ title: 'Read the briefing', step_type: 'info', text_content: 'Nothing to do.' }],
  });
  abandonScenarioId = abandonable.id;

  launchable = !!(await getAvailableScenario(learner, GATED_TITLE))?.launchable;
});

test.afterAll(async () => {
  for (const id of [gatedScenarioId, abandonScenarioId]) {
    if (!id) continue;
    await cleanupScenarioSession(learner, id).catch(() => {});
    if (orgId) await deleteScenario(trainer, orgId, id);
  }
  await trainer?.api.dispose();
  await learner?.api.dispose();
});

test('a failed verify keeps the learner on the step until the work is actually done', async ({
  page,
}) => {
  test.skip(!orgId, `trainer ${TRAINER_EMAIL} owns no team org — seed the dev personas first`);
  test.skip(
    !launchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  if (!(await launchFromLauncher(page, GATED_TITLE))) {
    test.skip(true, 'launch refused by the backend (likely host capacity)');
  }

  const stepTitle = page.getByTestId('scenario-step-title');
  await expect(stepTitle).toHaveText(GATED_STEP, { timeout: 60_000 });
  await waitForLiveTerminal(page);

  // Verify before doing the work: the check must fail, show what came back,
  // and leave the learner on this step.
  await page.getByTestId('scenario-verify-btn').click();
  const verifyResult = page.getByTestId('scenario-verify-result');
  await expect(verifyResult).toHaveClass(/failed/, { timeout: 30_000 });
  await expect(verifyResult.locator('.output-text')).toContainText('/tmp/e2e-ok is missing');
  await expect(stepTitle).toHaveText(GATED_STEP);

  // Now do it in the real container, and the same check passes.
  await typeInTerminal(page, 'touch /tmp/e2e-ok');
  await page.getByTestId('scenario-verify-btn').click();
  await expect(page.getByTestId('scenario-completed')).toBeVisible({ timeout: 60_000 });

  await expect
    .poll(
      async () => {
        const sessions = await getMyScenarioSessions(learner);
        return sessions.find((s: any) => s.scenario_id === gatedScenarioId)?.status;
      },
      { timeout: 30_000 }
    )
    .toBe('completed');
});

test('abandoning a run shows up as abandoned in the learner history', async ({ page }) => {
  test.skip(!orgId, `trainer ${TRAINER_EMAIL} owns no team org — seed the dev personas first`);
  test.skip(
    !launchable,
    'fixture not launchable — Tier B needs a live tt-backend + Incus with an apk distribution'
  );
  test.setTimeout(360_000);

  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  if (!(await launchFromLauncher(page, ABANDON_TITLE))) {
    test.skip(true, 'launch refused by the backend (likely host capacity)');
  }
  await expect(page.getByTestId('scenario-step-title')).toBeVisible({ timeout: 60_000 });

  await page.getByTestId('scenario-abandon-btn').click();
  await page.locator('.el-message-box__btns .el-button--primary').click();

  await navigateViaMenuCategory(page, 'terminals', '/my-scenarios');
  const historyEntry = page.locator('.scenario-group').filter({ hasText: ABANDON_TITLE });
  await expect(historyEntry).toBeVisible({ timeout: 30_000 });
  await expect(historyEntry.locator('.status-badge.abandoned')).toBeVisible();
});
