import { test, expect, type Page } from '@playwright/test';
import { login, switchToOrg } from './helpers/auth';
import { dismissVerificationBanner, navigateViaMenuCategory } from './helpers/ui';
import {
  apiLogin,
  importScenario,
  deleteScenarioById,
  getAvailableScenario,
  getMyScenarioSessions,
  getTerminalSession,
  cleanupScenarioSession,
  type ApiSession,
  type SeedScenario,
} from './helpers/scenarioApi';
import { readFlagFileFromTerminal, waitForLiveTerminal } from './helpers/xterm';
import { adminSession } from './helpers/freshUsers';
import { getOrganizations, orgDisplayName, type ApiOrganization } from './helpers/platformApi';

// ---------------------------------------------------------------------------
// Tier B — Stop on a scenario run whose terminal is NOT persistent.
//
// A non-persistent terminal cannot pause, so Stop takes the machine away,
// behind a confirm that says what happens to the run, and the page stays on it:
//   - a normal run keeps its progress: the page offers the rebuild, which
//     builds a new machine at the same step, with the same flag;
//   - a crash-trap run is its machine: Stop ends the run, and nothing offers
//     to resume it.
// Delete is not offered next to Stop there: it would do the same thing.
//
// The component test mocks the backend; this spec is the proof against the
// real one (ocf-core abandons AND deletes on the abandon endpoint — a mocked
// delete once hid a Stop that always failed).
//
// Requirements (local only): the same stack as scenario-pause-resume.spec.ts.
// The learner is not karim — whose plan must keep persistence for the pause
// spec — but E2E_EPHEMERAL_USER (default lea), working in their PERSONAL org
// (a team org would lend them its plan). Their personal plan is part of the
// fixture: a CPU/RAM budget for an xs machine and NO data persistence. The
// spec FAILS, loudly, when that plan is wrong, and SELF-SKIPS only on missing
// infrastructure.
// ---------------------------------------------------------------------------

const LEARNER_EMAIL = process.env.E2E_EPHEMERAL_USER || 'lea@test.ocf';
const PASSWORD = process.env.E2E_EPHEMERAL_PASS || 'OcfTest2026!';

const RUN_STAMP = Date.now().toString(36);
const FLAG_PATH = '/tmp/e2e-stop-flag';

const NORMAL_TITLE = `E2E stop ephemeral ${RUN_STAMP}`;
const CRASH_TRAPS_TITLE = `E2E stop crash traps ${RUN_STAMP}`;

function fixture(title: string, crashTraps: boolean): SeedScenario {
  return {
    title,
    description: 'Auto-generated by scenario-stop-ephemeral.spec.ts — safe to delete.',
    is_public: true,
    flags_enabled: true,
    crash_traps: crashTraps,
    intro_text: 'Welcome to the stop fixture.',
    finish_text: 'Fixture complete.',
    steps: [
      { title: 'Read the briefing', step_type: 'info', text_content: 'Just read and continue.' },
      {
        title: 'Capture the flag',
        step_type: 'flag',
        has_flag: true,
        flag_path: FLAG_PATH,
        text_content: 'The flag hides in /tmp — cat it and submit.',
      },
      { title: 'All done', step_type: 'info', text_content: 'You made it through a stop.' },
    ],
  };
}

let admin: ApiSession | null = null;
let learner: ApiSession;
let personalOrg: ApiOrganization;
const scenarioIds: Record<string, string> = {};
const cards: Record<string, { launchable: boolean; blockReason: string }> = {};

test.beforeAll(async () => {
  admin = await adminSession();
  learner = await apiLogin(LEARNER_EMAIL, PASSWORD);
  personalOrg = (await getOrganizations(learner)).find((o) => o.organization_type === 'personal')!;
  if (!admin) return;

  for (const [title, crashTraps] of [[NORMAL_TITLE, false], [CRASH_TRAPS_TITLE, true]] as const) {
    scenarioIds[title] = (await importScenario(admin, null, fixture(title, crashTraps))).id;
    const card = await getAvailableScenario(learner, title, personalOrg.id);
    cards[title] = { launchable: !!card?.launchable, blockReason: card?.block_reason || '' };
  }
});

test.afterAll(async () => {
  for (const id of Object.values(scenarioIds)) {
    await cleanupScenarioSession(learner, id).catch(() => {});
    if (admin) await deleteScenarioById(admin, id);
  }
  await admin?.api.dispose();
  await learner?.api.dispose();
});

function requireLaunchable(title: string) {
  test.skip(!admin, 'no platform admin to import the fixture — set E2E_ADMIN_EMAIL / E2E_ADMIN_PASSWORD');
  const { launchable, blockReason } = cards[title];
  expect(
    ['size_over_plan', 'budget_exhausted', 'plan'],
    `${LEARNER_EMAIL}'s plan cannot launch the fixture (${blockReason}) — give it a CPU/RAM budget`
  ).not.toContain(blockReason);
  test.skip(
    !launchable,
    `fixture not launchable (${blockReason}) — Tier B needs a live tt-backend + Incus with an apk distribution`
  );
}

// Launches the fixture from its card and passes step 1. Returns the terminal,
// after checking it is the kind this spec is about: not persistent.
async function launchNonPersistent(page: Page, title: string): Promise<string> {
  await login(page, LEARNER_EMAIL, PASSWORD);
  await dismissVerificationBanner(page);
  await switchToOrg(page, orgDisplayName(personalOrg));
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');

  const card = page.getByTestId('scenario-card').filter({ hasText: title });
  await expect(card).toBeVisible({ timeout: 15_000 });
  await card.getByTestId('scenario-launch-btn').or(card.getByTestId('scenario-relaunch-btn')).click();

  const errorToast = page.locator('.el-notification');
  await Promise.race([
    page.waitForURL(/\/terminal-session\//, { timeout: 240_000 }),
    errorToast.waitFor({ state: 'visible', timeout: 240_000 }),
  ]);
  if (!/\/terminal-session\//.test(page.url())) {
    const toastText = (await errorToast.innerText().catch(() => '')) || 'launch refused';
    test.skip(true, `launch refused by the backend (likely host capacity): ${toastText.slice(0, 120)}`);
  }
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Read the briefing', { timeout: 60_000 });
  await page.getByTestId('scenario-info-ack').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', { timeout: 30_000 });
  await waitForLiveTerminal(page);

  const terminalId = page.url().split('/terminal-session/')[1]?.split(/[?#]/)[0];
  const terminal = await getTerminalSession(learner, terminalId);
  expect(
    terminal?.persistence_mode,
    `${LEARNER_EMAIL}'s effective plan has data persistence — this spec needs a plan without it`
  ).not.toBe('persistent');
  return terminalId;
}

// Stop, as the learner sees it on a non-persistent run: only Stop is offered,
// and it asks first — in words of a stop — with the given copy.
async function stopWithConfirm(page: Page, copy: RegExp) {
  // The accessible name carries the icon glyph before the label.
  await expect(page.getByRole('button', { name: /(Destroy|Détruire)$/ })).toHaveCount(0);
  const stopButton = page.getByRole('button', { name: /(Stop|Arrêter)$/ });
  await expect(stopButton).toBeEnabled({ timeout: 15_000 });
  await stopButton.click();

  const confirm = page.locator('.base-modal-container');
  await expect(confirm).toContainText(copy);
  const cta = page.getByTestId('confirm-delete-cta');
  await expect(cta).toHaveText(/(Stop|Arrêter)$/);
  await cta.click();
}

async function runOf(title: string) {
  const sessions = await getMyScenarioSessions(learner);
  return sessions
    .filter((s) => s.scenario_id === scenarioIds[title])
    .sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)))[0];
}

test('learner stops a non-persistent run, rebuilds it and resumes at the same step', async ({ page }) => {
  requireLaunchable(NORMAL_TITLE);
  // Launch, then a rebuild (a new terminal plus the replay) and step transitions.
  test.setTimeout(600_000);

  const terminalId = await launchNonPersistent(page, NORMAL_TITLE);
  const flagBefore = await readFlagFileFromTerminal(page, FLAG_PATH);

  await stopWithConfirm(page, /rebuilt at this step|reconstruit à cette étape/i);

  // The page stays on the run and offers the rebuild over the dead console.
  const rebuild = page.getByTestId('rebuild-session-cta');
  await expect(rebuild).toBeVisible({ timeout: 60_000 });
  expect(page.url()).toContain(terminalId);
  await expect(page.getByTestId('resume-session-cta')).toHaveCount(0);
  await expect
    .poll(async () => {
      const run = await runOf(NORMAL_TITLE);
      return run && { status: run.status, resume_mode: run.resume_mode };
    }, { timeout: 30_000 })
    .toEqual({ status: 'active', resume_mode: 'rebuild' });

  await rebuild.click();
  // A new terminal replaces the stopped one.
  await page.waitForURL(
    (url) => url.pathname.includes('/terminal-session/') && !url.pathname.includes(terminalId),
    { timeout: 300_000 }
  );

  // Same step, and the same flag re-planted on the new machine.
  await expect(page.getByTestId('scenario-step-title')).toHaveText('Capture the flag', { timeout: 120_000 });
  await waitForLiveTerminal(page, 120_000);
  const flagAfter = await readFlagFileFromTerminal(page, FLAG_PATH);
  expect(flagAfter).toBe(flagBefore);
  await page.getByTestId('scenario-flag-input').fill(flagAfter);
  await page.getByTestId('scenario-flag-submit').click();
  await expect(page.getByTestId('scenario-step-title')).toHaveText('All done', { timeout: 30_000 });
});

test('learner stops a non-persistent crash-trap run, which ends it for good', async ({ page }) => {
  requireLaunchable(CRASH_TRAPS_TITLE);
  test.setTimeout(360_000);

  await launchNonPersistent(page, CRASH_TRAPS_TITLE);

  await stopWithConfirm(page, /ends this run|met fin à cette session/i);

  // The run is over — ended by the learner, not left for the cleanup cron —
  // and the page says so, with nothing to resume or rebuild.
  await expect.poll(async () => (await runOf(CRASH_TRAPS_TITLE))?.status, { timeout: 30_000 }).toBe('abandoned');
  await expect(page.getByText(/Scenario Abandoned|Scénario abandonné/)).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId('rebuild-session-cta')).toHaveCount(0);
  await expect(page.getByTestId('resume-session-cta')).toHaveCount(0);

  // From the launcher, the scenario starts over: no resume of the ended run.
  await navigateViaMenuCategory(page, 'scenarios', '/scenarios');
  const card = page.getByTestId('scenario-card').filter({ hasText: CRASH_TRAPS_TITLE });
  await expect(card.getByTestId('scenario-launch-btn').or(card.getByTestId('scenario-relaunch-btn'))).toBeVisible({
    timeout: 15_000,
  });
  await expect(card.getByTestId('scenario-resume-btn')).toHaveCount(0);
  await expect(card.getByTestId('scenario-rebuild-btn')).toHaveCount(0);
});
