export { default as GroupOverviewTab } from './GroupOverviewTab.vue'
export { default as GroupMembersManager } from './GroupMembersManager.vue'
export { default as GroupSettingsTab } from './GroupSettingsTab.vue'
export { default as GroupCommandHistory } from './GroupCommandHistory.vue'
export { default as GroupScenariosTab } from './GroupScenariosTab.vue'
export { default as GroupActivityTab } from './GroupActivityTab.vue'
export { default as GroupAnalyticsTab } from './GroupAnalyticsTab.vue'
